### ISSUE TITLE
Development todo list

### ISSUE THREAD

**Issue by MauriceHendrix** [CardiacModelling/ap-nimbus-client#6]
- [x] General project architecture see #7
- [x] Client project setup
    - [x] Set up django project in docker
    - [x] Make sure tests can run locally
    - [x] Set up automated testing on PRs
    - [x] Make sure static content is servec
    - [x] Set up basic version of home, privacy and contact page
- [x] Write static pages
    - [x] home
    - [x] privacy
    - [x] contact
- [x] Create user register and login functionality (inspired by weblab)
- [x] Cellml file management
    - [x] Allow upload
    - [x] Provide a setting for predefined (moderated) models
    - [x] Populate predefined models automaticly
- [x] Create form to start simulation
    - [x] With cellml upload
    - [x] With pk file upload
    - [x] markdown in notes
    - [x] list of simulations & results
    - [x] edit notes/title
    - [x] delete simulation
    - [x] rerun simulation
- [x] Build connection to app-manager
    - [x] build initial request
    - [x] retrive results
    - [x] app manager api missing features
        - [x] allow IC50 instad of pIC50 & units
        - [x] is call without spead_of_uncertainty possible
        - [x] deal with pk_data file
        - [x] deal with cellml file
        - [x] delete files after simulation results are receievd
- [x] Change site design colour scheme?
- [x]  Consider security of uploading files (see #1)

**Comment by flawmop** [comment]
This seems to be completed, so closing.
